/* ================= Stage definitions (visual + musical identity) ================= */
const E16 = (s) => s.split('').map((c) => (c === 'x' ? 1 : c === 'o' ? 2 : 0));
const STAGES = [
  {
    id: 'sushi', name: 'Kaiten Sushi', sub: 'Conveyor-belt izakaya at dusk',
    desc: 'Lanterns, a busy itamae, sake shelves and a belt of hand-drawn sushi — koto, shakuhachi and taiko.',
    accent: '#ffb35c', accent2: '#e8c04a', skin: 'sushi', particle: 'petal',
    boardBg: 'rgba(16,7,4,0.82)', grid: 'rgba(255,190,120,0.06)',
    palette: ['#a9bccf', '#f5c842', '#f0561a', '#7cc254', '#c8203a', '#b0447a', '#f57a3d'],
    music: {
      bpm: 88, root: 62, scale: [0, 2, 5, 7, 9], prog: [0, 3, 1, 4], barsPerChord: 1,
      pad: { wave: 'sawtooth', cutoff: 950, gain: 0.05, detune: 6, voices: 3, oct: -1 },
      arp: { inst: 'koto', pattern: [0, 2, 4, 2, 5, 4, 2, 1], every: 2, oct: 0, gain: 0.11, density: 0.7 },
      bass: { pattern: E16('x.....x...x.....'), gain: 0.16, dec: 0.6, wave: 'triangle' },
      drums: { kickInst: 'taiko', kick: E16('x.......x.x.....'), snareInst: 'wood', snare: E16('....x.......x..x'), hatInst: 'shaker', hat: E16('..x...x...x...x.'), extra: E16('.x.x.x.x.x.x.x.x'), extraInst: 'wood' },
      lead: { inst: 'flute', gain: 0.07, density: 0.1, oct: 1 }, sfx: 'koto',
    },
  },
  {
    id: 'ocean', name: 'Ocean Deep', sub: 'Bioluminescent abyss',
    desc: 'God-rays, drifting jellyfish and a passing whale, in a slow dorian key.',
    accent: '#5ff4ff', accent2: '#ff7ad9', skin: 'glass', particle: 'bubble',
    boardBg: 'rgba(1,16,30,0.74)', grid: 'rgba(120,230,255,0.07)',
    palette: ['#3fe9ff', '#ffe36a', '#c77dff', '#5dffa8', '#ff6a9a', '#4a8cff', '#ffa24a'],
    music: {
      bpm: 72, root: 50, scale: [0, 2, 3, 5, 7, 9, 10], prog: [0, 3, 5, 4], barsPerChord: 2,
      pad: { wave: 'triangle', cutoff: 1500, gain: 0.09, detune: 9, voices: 4 },
      arp: { inst: 'glass', pattern: [0, 2, 4, 7, 4, 2, 9, 4], every: 2, oct: 1, gain: 0.05, density: 0.55 },
      bass: { pattern: E16('x.......x.....o.'), gain: 0.18, dec: 1.2 },
      drums: { kick: E16('x.........x.....'), hat: E16('....x.......x...'), extra: E16('..x.....x.....x.'), extraInst: 'bell' },
      lead: { inst: 'glass', gain: 0.04, density: 0.08, oct: 2 }, sfx: 'glass',
    },
  },
  {
    id: 'desert', name: 'Desert Sunset', sub: 'Dunes under a burning sky',
    desc: 'Scrolling dunes, mesas, a camel caravan and drifting sand — oud and darbuka in Hijaz.',
    accent: '#ff9a4a', accent2: '#ffd36a', skin: 'sandstone', particle: 'sand',
    boardBg: 'rgba(30,10,10,0.72)', grid: 'rgba(255,200,140,0.07)',
    palette: ['#4fc3c8', '#f2c14e', '#b85c8a', '#8fae4a', '#d9483b', '#3f6fb0', '#e8843a'],
    music: {
      bpm: 94, root: 52, scale: [0, 1, 4, 5, 7, 8, 10], prog: [0, 0, 6, 5], barsPerChord: 1,
      pad: { wave: 'sawtooth', cutoff: 1100, gain: 0.05, detune: 8, voices: 3 },
      arp: { inst: 'oud', pattern: [0, 1, 2, 1, 4, 2, 1, 0], every: 2, oct: 0, gain: 0.12, density: 0.65 },
      bass: { pattern: E16('x..x..x.x.......'), gain: 0.18, dec: 0.45 },
      drums: { kickInst: 'darbuka', kick: E16('x.....x...x.....'), snareInst: 'darbuka', snare: E16('...x..x.x...x.x.'), hatInst: 'shaker', hat: E16('x.xxx.xxx.xxx.xx') },
      lead: { inst: 'flute', gain: 0.06, density: 0.12, oct: 1 }, sfx: 'oud',
    },
  },
  {
    id: 'neon', name: 'Neon City', sub: 'Synthwave rain at midnight',
    desc: 'Rain-soaked skyline, flickering neon kanji and an endless grid — saw arps and four-on-the-floor.',
    accent: '#ff3ad0', accent2: '#00f0ff', skin: 'neon', particle: 'spark',
    boardBg: 'rgba(8,0,20,0.78)', grid: 'rgba(255,80,220,0.09)',
    palette: ['#00f0ff', '#ffe14a', '#c84bff', '#3dff7a', '#ff2b6a', '#3a6bff', '#ff8a2a'],
    music: {
      bpm: 112, root: 45, scale: [0, 2, 3, 5, 7, 8, 10], prog: [0, 5, 2, 6], barsPerChord: 1,
      pad: { wave: 'sawtooth', cutoff: 1800, gain: 0.05, detune: 12, voices: 4 },
      arp: { inst: 'saw', pattern: [0, 2, 4, 7, 4, 2, 0, 2], every: 1, oct: 1, gain: 0.05, density: 0.85 },
      bass: { pattern: E16('x.x.x.x.x.x.x.x.'), gain: 0.16, dec: 0.18, wave: 'sawtooth' },
      drums: { kick: E16('x...x...x...x...'), snare: E16('....x.......x...'), hat: E16('..x...x...x...x.'), extra: E16('x.x.x.x.x.x.x.x.') },
      lead: { inst: 'saw', gain: 0.05, density: 0.1, oct: 2 }, sfx: 'saw',
    },
  },
  {
    id: 'aurora', name: 'Aurora Forest', sub: 'Northern lights over silent pines',
    desc: 'Rippling aurora curtains, snowfall and fireflies over layered forests — lydian bells.',
    accent: '#5dffb0', accent2: '#b46aff', skin: 'ice', particle: 'snow',
    boardBg: 'rgba(2,12,22,0.74)', grid: 'rgba(150,255,210,0.07)',
    palette: ['#7af7ff', '#fff07a', '#c8a2ff', '#6affb4', '#ff8aa8', '#6a9bff', '#ffc27a'],
    music: {
      bpm: 76, root: 53, scale: [0, 2, 4, 6, 7, 9, 11], prog: [0, 1, 5, 4], barsPerChord: 2,
      pad: { wave: 'triangle', cutoff: 2200, gain: 0.08, detune: 6, voices: 4 },
      arp: { inst: 'bell', pattern: [0, 4, 2, 6, 4, 7, 2, 9], every: 2, oct: 1, gain: 0.05, density: 0.6 },
      bass: { pattern: E16('x.......x.......'), gain: 0.16, dec: 1.4 },
      drums: { kick: E16('x.........x.....'), hat: E16('....x.......x...'), extra: E16('......x.......x.'), extraInst: 'bell' },
      lead: { inst: 'bell', gain: 0.04, density: 0.07, oct: 2 }, sfx: 'pluck',
    },
  },
  {
    id: 'cosmic', name: 'Cosmic Nebula', sub: 'Adrift between the stars',
    desc: 'A slowly turning nebula, ringed planet, comets and warp-streak stars — whole-tone shimmer.',
    accent: '#b38aff', accent2: '#5ad8ff', skin: 'gem', particle: 'star',
    boardBg: 'rgba(6,2,18,0.74)', grid: 'rgba(190,150,255,0.08)',
    palette: ['#5ad8ff', '#ffd86a', '#d17aff', '#6affc8', '#ff5a8a', '#6a7aff', '#ff9a5a'],
    music: {
      bpm: 100, root: 48, scale: [0, 2, 4, 6, 8, 10], prog: [0, 1, 0, 5], barsPerChord: 2,
      pad: { wave: 'sawtooth', cutoff: 1400, gain: 0.06, detune: 14, voices: 3 },
      arp: { inst: 'glass', pattern: [0, 2, 4, 6, 4, 2], every: 1, oct: 1, gain: 0.04, density: 0.7 },
      bass: { pattern: E16('x.......x..x....'), gain: 0.18, dec: 0.9 },
      drums: { kick: E16('x.......x.......'), snare: E16('....x.......x...'), hat: E16('x.x.x.x.x.x.x.x.'), extra: E16('...x.....x...x..'), extraInst: 'bell' },
      lead: { inst: 'bell', gain: 0.045, density: 0.1, oct: 2 }, sfx: 'bell',
    },
  },
];
const LINES_PER_STAGE = 12;
