/* ================= Stage definitions (visual + musical identity) ================= */
const E16 = (s) => s.split('').map((c) => (c === 'x' ? 1 : c === 'o' ? 2 : 0));
const STAGES = [
  {
    id: 'sushi', name: 'Kaiten Sushi', sub: 'Conveyor-belt sushi, lunch to late night',
    desc: 'Flat mid-century geometry: paper lanterns, a busy itamae, regulars coming and going and a belt of true-colour sushi — koto, shakuhachi and taiko.',
    accent: '#ffb35c', accent2: '#e8c04a', skin: 'sushi', particle: 'petal',
    boardBg: 'rgba(16,7,4,0.82)', grid: 'rgba(255,190,120,0.06)',
    palette: ['#f0561e', '#f5c842', '#f7905a', '#c8203a', '#7cc254', '#8fa8c4', '#eae4d4'], // I ikura · O tamago · T salmon · S maguro · Z edamame · J saba · L avocado maki
    music: {
      bpm: 88, root: 62, scale: [0, 2, 5, 7, 9], prog: [0, 3, 1, 4], barsPerChord: 1,
      pad: { wave: 'sawtooth', cutoff: 950, gain: 0.05, detune: 6, voices: 3, oct: -1 },
      arp: { inst: 'koto', pattern: [0, 2, 4, 2, 5, 4, 2, 1], every: 2, oct: 0, gain: 0.11, density: 0.7 },
      bass: { pattern: E16('x.....x...x.....'), gain: 0.16, dec: 0.6, wave: 'triangle' },
      drums: { kickInst: 'taiko', kick: E16('x.......x.x.....'), snareInst: 'wood', snare: E16('....x.......x..x'), hatInst: 'shaker', hat: E16('..x...x...x...x.'), extra: E16('.x.x.x.x.x.x.x.x'), extraInst: 'wood' },
      lead: { inst: 'flute', gain: 0.07, density: 0.1, oct: 1 }, sfx: 'koto',
    },
  },
  {
    id: 'mikes', name: "Mike's Pastry", sub: 'Hanover Street, North End, Boston',
    desc: 'Pressed-tin ceiling, glass cases of cannoli and lobster tails, boxes tied with blue-and-white string — mandolin & accordion.',
    accent: '#7ab8ff', accent2: '#ffd36a', skin: 'pastry', particle: 'sugar',
    boardBg: 'rgba(20,24,40,0.78)', grid: 'rgba(170,210,255,0.08)',
    palette: ['#f6c9d3', '#a9cdec', '#cdb8ec', '#acdfb6', '#f6e0a4', '#f8bc96', '#e2b07e'],
    music: {
      bpm: 104, root: 55, scale: [0, 2, 4, 5, 7, 9, 11], prog: [0, 3, 4, 0], barsPerChord: 1,
      pad: { wave: 'square', cutoff: 1300, gain: 0.03, detune: 6, voices: 3, oct: -1 },
      arp: { inst: 'mandolin', pattern: [0, 2, 4, 2, 7, 4, 2, 4], every: 2, oct: 1, gain: 0.05, density: 0.75 },
      comp: { inst: 'accordion', pattern: E16('....x.......x...'), voices: 3, gain: 0.035, oct: 0, len: 2 },
      bass: { pattern: E16('x.......o.......'), gain: 0.16, dec: 0.4, wave: 'triangle' },
      drums: { hatInst: 'shaker', hat: E16('..x...x...x...x.'), snareInst: 'wood', snare: E16('....x.......x...') },
      lead: { inst: 'accordion', gain: 0.04, density: 0.1, oct: 1 }, sfx: 'mandolin', clearFx: 'sugar',
      amb: { chatter: 0.02, clink: 0.04 },
    },
  },
  {
    id: 'speakeasy', name: 'The Speakeasy', sub: '1920s · password at the door',
    desc: 'Amber Edison bulbs, a mahogany back bar, a jazz trio and a flapper — swinging upright bass, brushes and muted horn.',
    accent: '#e8b45a', accent2: '#c0283a', skin: 'cocktail', particle: 'champagne',
    boardBg: 'rgba(14,8,4,0.82)', grid: 'rgba(230,180,90,0.07)',
    palette: ['#c8701a', '#cfd8c8', '#f4dc84', '#9ad070', '#8a2410', '#d8341c', '#8ad040'],
    music: {
      bpm: 128, swing: 0.32, root: 53, scale: [0, 2, 4, 5, 7, 9, 11], prog: [1, 4, 0, 5], barsPerChord: 1,
      pad: { wave: 'triangle', cutoff: 900, gain: 0.025, detune: 4, voices: 4, oct: -1 },
      comp: { inst: 'piano', pattern: E16('x.....x.........'), voices: 4, gain: 0.04, oct: 0, strum: 0.008 },
      bass: { pattern: E16('x...x...x...x...'), walk: true, inst: 'upbass', gain: 0.24, dec: 0.4, oct: -1 },
      drums: { hatInst: 'ride', hat: E16('x...x.x.x...x.x.'), snareInst: 'brush', snare: E16('....x.......x...'), kick: E16('x.........x.....') },
      lead: { inst: 'horn', gain: 0.05, density: 0.16, oct: 1 }, sfx: 'piano', clearFx: 'pop',
      amb: { chatter: 0.022, clink: 0.12 },
    },
  },
  {
    id: 'dimsum', name: 'Dim Sum Palace', sub: 'Yum cha in the golden banquet hall',
    desc: 'Dragon & phoenix wall, chandeliers, aunties pushing steaming trolleys between round tables — guzheng and erhu.',
    accent: '#ffcc4a', accent2: '#e8302a', skin: 'dimsum', particle: 'steam',
    boardBg: 'rgba(40,6,6,0.78)', grid: 'rgba(255,210,120,0.08)',
    palette: ['#f4e8dc', '#f6d850', '#f6efe2', '#eee4d0', '#f8d040', '#eeeae2', '#e09a3a'],
    music: {
      bpm: 84, root: 55, scale: [0, 2, 4, 7, 9], prog: [0, 3, 1, 4], barsPerChord: 1,
      pad: { wave: 'triangle', cutoff: 1400, gain: 0.05, detune: 6, voices: 3 },
      arp: { inst: 'guzheng', pattern: [0, 1, 2, 4, 3, 2, 1, 2], every: 2, oct: 1, gain: 0.08, density: 0.65 },
      bass: { pattern: E16('x.......x.....o.'), gain: 0.15, dec: 0.8 },
      drums: { snareInst: 'wood', snare: E16('....x.......x.x.'), hatInst: 'shaker', hat: E16('..x...x...x...x.'), kick: E16('x.........x.....') },
      lead: { inst: 'erhu', gain: 0.05, density: 0.12, oct: 1 }, sfx: 'guzheng', clearFx: 'lid',
      amb: { chatter: 0.03, clink: 0.06, lid: 0.04 },
    },
  },
  {
    id: 'gelato', name: 'Gelateria', sub: 'Twenty flavours and a waffle iron',
    desc: 'A curved case of sculpted gelato tins, pastel tiles and a real queue — light bossa with nylon guitar and vibes.',
    accent: '#ff8ab8', accent2: '#7ae0d0', skin: 'gelato', particle: 'sprinkle',
    boardBg: 'rgba(30,14,30,0.74)', grid: 'rgba(255,190,220,0.08)',
    palette: ['#a8c878', '#fbf6ea', '#f6a0b4', '#ffb43a', '#6a3a1c', '#a07ac8', '#fbec8a'],
    music: {
      bpm: 124, root: 57, scale: [0, 2, 4, 5, 7, 9, 11], prog: [0, 5, 1, 4], barsPerChord: 1,
      pad: { wave: 'triangle', cutoff: 1800, gain: 0.03, detune: 5, voices: 4 },
      comp: { inst: 'nylon', pattern: E16('x..x..x...x..x..'), voices: 4, gain: 0.04, oct: 0, strum: 0.012 },
      bass: { pattern: E16('x.....o.x.....o.'), gain: 0.16, dec: 0.5 },
      drums: { hatInst: 'shaker', hat: E16('xxxxxxxxxxxxxxxx'), snareInst: 'wood', snare: E16('x..x..x...x..x..'), kick: E16('x.......x.......') },
      lead: { inst: 'vibes', gain: 0.05, density: 0.12, oct: 1 }, sfx: 'vibes', clearFx: 'sugar',
      amb: { chatter: 0.014, clink: 0.03 },
    },
  },
  {
    id: 'fishhouse', name: 'The Fish House', sub: 'Candlelit, Michelin-starred, harbour at dusk',
    desc: 'A towering raw bar, a live lobster tank, an open kitchen and cloches lifted tableside — string quartet & piano.',
    accent: '#8ad8e8', accent2: '#f0d08a', skin: 'seafood', particle: 'pearl',
    boardBg: 'rgba(4,14,22,0.8)', grid: 'rgba(150,220,240,0.07)',
    palette: ['#6a9ab8', '#c8402a', '#e8b04a', '#e8d890', '#a8682a', '#f0805a', '#5a5a8a'],
    music: {
      bpm: 76, root: 51, scale: [0, 2, 4, 5, 7, 9, 11], prog: [0, 5, 3, 4], barsPerChord: 2,
      pad: { wave: 'sawtooth', cutoff: 1100, gain: 0.03, detune: 9, voices: 4 },
      comp: { inst: 'strings', pattern: E16('x...............'), voices: 4, gain: 0.03, oct: 0, len: 16 },
      arp: { inst: 'piano', pattern: [0, 4, 2, 7, 4, 9, 2, 4], every: 2, oct: 1, gain: 0.06, density: 0.5 },
      bass: { pattern: E16('x.......x.......'), inst: 'upbass', gain: 0.18, dec: 0.6 },
      drums: { hatInst: 'brush', hat: E16('x...x...x...x...') },
      lead: { inst: 'strings', gain: 0.035, density: 0.08, oct: 1 }, sfx: 'piano', clearFx: 'clink',
      amb: { chatter: 0.012, clink: 0.16 },
    },
  },
  {
    id: 'pizzeria', name: 'Trattoria', sub: 'Wood-fired oven, checkered cloths, Chianti',
    desc: 'A glowing dome oven, a pizzaiolo tossing dough, pasta flaring in the pan — a tarantella lilt on mandolin & accordion.',
    accent: '#ff7a3a', accent2: '#5ac85a', skin: 'pizza', particle: 'basil',
    boardBg: 'rgba(28,10,4,0.8)', grid: 'rgba(255,170,110,0.08)',
    palette: ['#e84a2a', '#a8201a', '#f0b040', '#e8c878', '#e8dca8', '#d0502a', '#b85a2a'],
    music: {
      bpm: 132, swing: 0.3, root: 57, scale: [0, 2, 3, 5, 7, 8, 11], prog: [0, 3, 4, 0], barsPerChord: 1,
      pad: { wave: 'square', cutoff: 1100, gain: 0.025, detune: 7, voices: 3, oct: -1 },
      arp: { inst: 'mandolin', pattern: [0, 2, 4, 2, 4, 7, 4, 2], every: 2, oct: 1, gain: 0.05, density: 0.85 },
      comp: { inst: 'accordion', pattern: E16('..x...x...x...x.'), voices: 3, gain: 0.03, oct: 0, len: 1 },
      bass: { pattern: E16('x.......o.......'), gain: 0.17, dec: 0.35, wave: 'triangle' },
      drums: { hatInst: 'shaker', hat: E16('x.xxx.xxx.xxx.xx'), kick: E16('x.......x.......'), snareInst: 'wood', snare: E16('....x.......x...') },
      lead: { inst: 'accordion', gain: 0.04, density: 0.12, oct: 1 }, sfx: 'mandolin', clearFx: 'sizzle',
      amb: { chatter: 0.022, clink: 0.06, sizzle: 0.03 },
    },
  },
  {
    id: 'fastfood', name: 'Golden Arches', sub: 'A fast-food classic (fan tribute)',
    desc: 'Menu boards, kiosks, fryers beeping, a grill line and a drive-thru — a bouncy, original pop jingle-ish groove.',
    accent: '#ffc72c', accent2: '#e8241a', skin: 'fastfood', particle: 'fries',
    boardBg: 'rgba(40,8,6,0.78)', grid: 'rgba(255,200,60,0.08)',
    palette: ['#b01c16', '#f0b41c', '#f4ece0', '#2a6ac0', '#8a4a1a', '#e47ab0', '#169a9a'],
    music: {
      bpm: 118, root: 60, scale: [0, 2, 4, 5, 7, 9, 11], prog: [0, 4, 5, 3], barsPerChord: 1,
      pad: { wave: 'sawtooth', cutoff: 2000, gain: 0.035, detune: 10, voices: 3 },
      comp: { inst: 'square', pattern: E16('..x...x...x...x.'), voices: 3, gain: 0.03, oct: 0 },
      arp: { inst: 'square', pattern: [0, 2, 4, 7, 4, 2, 4, 9], every: 2, oct: 1, gain: 0.03, density: 0.6 },
      bass: { pattern: E16('x..x..x.x..x..x.'), gain: 0.17, dec: 0.25, wave: 'square' },
      drums: { kick: E16('x...x...x...x...'), snareInst: 'clap', snare: E16('....x.......x...'), hat: E16('..x...x...x...x.') },
      lead: { inst: 'rhodes', gain: 0.05, density: 0.14, oct: 1 }, sfx: 'square', clearFx: 'sizzle',
      amb: { chatter: 0.018, beep: 0.07, sizzle: 0.04 },
    },
  },
  {
    id: 'ocean', name: 'Ocean Deep', sub: 'Bioluminescent abyss',
    desc: 'God-rays, drifting jellyfish and a passing whale, in a slow dorian key.',
    accent: '#5ff4ff', accent2: '#ff7ad9', skin: 'glass', particle: 'bubble',
    boardBg: 'rgba(1,16,30,0.74)', grid: 'rgba(120,230,255,0.07)',
    palette: ['#3fe9ff', '#ffe36a', '#c77dff', '#5dffa8', '#ff6a9a', '#4a8cff', '#ffa24a'],
    music: {
      bpm: 72, root: 50, scale: [0, 2, 3, 5, 7, 9, 10], prog: [0, 3, 5, 4], barsPerChord: 2,
      pad: { wave: 'triangle', cutoff: 1500, gain: 0.09, detune: 9, voices: 4 },
      arp: { inst: 'glass', pattern: [0, 2, 4, 7, 4, 2, 9, 4], every: 2, oct: 1, gain: 0.05, density: 0.55 },
      bass: { pattern: E16('x.......x.....o.'), gain: 0.18, dec: 1.2 },
      drums: { kick: E16('x.........x.....'), hat: E16('....x.......x...'), extra: E16('..x.....x.....x.'), extraInst: 'bell' },
      lead: { inst: 'glass', gain: 0.04, density: 0.08, oct: 2 }, sfx: 'glass',
    },
  },
  {
    id: 'desert', name: 'Desert Sunset', sub: 'Dunes under a burning sky',
    desc: 'Scrolling dunes, mesas, a camel caravan and drifting sand — oud and darbuka in Hijaz.',
    accent: '#ff9a4a', accent2: '#ffd36a', skin: 'sandstone', particle: 'sand',
    boardBg: 'rgba(30,10,10,0.72)', grid: 'rgba(255,200,140,0.07)',
    palette: ['#4fc3c8', '#f2c14e', '#b85c8a', '#8fae4a', '#d9483b', '#3f6fb0', '#e8843a'],
    music: {
      bpm: 94, root: 52, scale: [0, 1, 4, 5, 7, 8, 10], prog: [0, 0, 6, 5], barsPerChord: 1,
      pad: { wave: 'sawtooth', cutoff: 1100, gain: 0.05, detune: 8, voices: 3 },
      arp: { inst: 'oud', pattern: [0, 1, 2, 1, 4, 2, 1, 0], every: 2, oct: 0, gain: 0.12, density: 0.65 },
      bass: { pattern: E16('x..x..x.x.......'), gain: 0.18, dec: 0.45 },
      drums: { kickInst: 'darbuka', kick: E16('x.....x...x.....'), snareInst: 'darbuka', snare: E16('...x..x.x...x.x.'), hatInst: 'shaker', hat: E16('x.xxx.xxx.xxx.xx') },
      lead: { inst: 'flute', gain: 0.06, density: 0.12, oct: 1 }, sfx: 'oud',
    },
  },
  {
    id: 'neon', name: 'Neon City', sub: 'Synthwave rain at midnight',
    desc: 'Rain-soaked skyline, flickering neon kanji and an endless grid — saw arps and four-on-the-floor.',
    accent: '#ff3ad0', accent2: '#00f0ff', skin: 'neon', particle: 'spark',
    boardBg: 'rgba(8,0,20,0.78)', grid: 'rgba(255,80,220,0.09)',
    palette: ['#00f0ff', '#ffe14a', '#c84bff', '#3dff7a', '#ff2b6a', '#3a6bff', '#ff8a2a'],
    music: {
      bpm: 112, root: 45, scale: [0, 2, 3, 5, 7, 8, 10], prog: [0, 5, 2, 6], barsPerChord: 1,
      pad: { wave: 'sawtooth', cutoff: 1800, gain: 0.05, detune: 12, voices: 4 },
      arp: { inst: 'saw', pattern: [0, 2, 4, 7, 4, 2, 0, 2], every: 1, oct: 1, gain: 0.05, density: 0.85 },
      bass: { pattern: E16('x.x.x.x.x.x.x.x.'), gain: 0.16, dec: 0.18, wave: 'sawtooth' },
      drums: { kick: E16('x...x...x...x...'), snare: E16('....x.......x...'), hat: E16('..x...x...x...x.'), extra: E16('x.x.x.x.x.x.x.x.') },
      lead: { inst: 'saw', gain: 0.05, density: 0.1, oct: 2 }, sfx: 'saw',
    },
  },
  {
    id: 'aurora', name: 'Aurora Forest', sub: 'Northern lights over silent pines',
    desc: 'Rippling aurora curtains, snowfall and fireflies over layered forests — lydian bells.',
    accent: '#5dffb0', accent2: '#b46aff', skin: 'ice', particle: 'snow',
    boardBg: 'rgba(2,12,22,0.74)', grid: 'rgba(150,255,210,0.07)',
    palette: ['#7af7ff', '#fff07a', '#c8a2ff', '#6affb4', '#ff8aa8', '#6a9bff', '#ffc27a'],
    music: {
      bpm: 76, root: 53, scale: [0, 2, 4, 6, 7, 9, 11], prog: [0, 1, 5, 4], barsPerChord: 2,
      pad: { wave: 'triangle', cutoff: 2200, gain: 0.08, detune: 6, voices: 4 },
      arp: { inst: 'bell', pattern: [0, 4, 2, 6, 4, 7, 2, 9], every: 2, oct: 1, gain: 0.05, density: 0.6 },
      bass: { pattern: E16('x.......x.......'), gain: 0.16, dec: 1.4 },
      drums: { kick: E16('x.........x.....'), hat: E16('....x.......x...'), extra: E16('......x.......x.'), extraInst: 'bell' },
      lead: { inst: 'bell', gain: 0.04, density: 0.07, oct: 2 }, sfx: 'pluck',
    },
  },
  {
    id: 'cosmic', name: 'Cosmic Nebula', sub: 'Adrift between the stars',
    desc: 'A slowly turning nebula, ringed planet, comets and warp-streak stars — whole-tone shimmer.',
    accent: '#b38aff', accent2: '#5ad8ff', skin: 'gem', particle: 'star',
    boardBg: 'rgba(6,2,18,0.74)', grid: 'rgba(190,150,255,0.08)',
    palette: ['#5ad8ff', '#ffd86a', '#d17aff', '#6affc8', '#ff5a8a', '#6a7aff', '#ff9a5a'],
    music: {
      bpm: 100, root: 48, scale: [0, 2, 4, 6, 8, 10], prog: [0, 1, 0, 5], barsPerChord: 2,
      pad: { wave: 'sawtooth', cutoff: 1400, gain: 0.06, detune: 14, voices: 3 },
      arp: { inst: 'glass', pattern: [0, 2, 4, 6, 4, 2], every: 1, oct: 1, gain: 0.04, density: 0.7 },
      bass: { pattern: E16('x.......x..x....'), gain: 0.18, dec: 0.9 },
      drums: { kick: E16('x.......x.......'), snare: E16('....x.......x...'), hat: E16('x.x.x.x.x.x.x.x.'), extra: E16('...x.....x...x..'), extraInst: 'bell' },
      lead: { inst: 'bell', gain: 0.045, density: 0.1, oct: 2 }, sfx: 'bell',
    },
  },
];
const LINES_PER_STAGE = 10;
